[sdl]
fullscreen=false
output=surface
autolock=false
waitonerror=false
priority=highest,highest

[dosbox]
machine=cga
memsize=16

[render]
frameskip=0
aspect=false
scaler=none

[cpu]
core=normal
cycles=3000

[autoexec]
mount c /vmstore/claude/monopoly/game-det
c:
MONOPOLY.COM
