"""Prove the CGA renderer is pixel-exact against the real emulator.

Method: take a screenshot of the 1985 program running under DOSBox, decode it
back into an 80x25 grid of (character, attribute) cells, re-render that grid
with monopoly.cga, and diff the result against the original capture.

A zero-pixel diff establishes three things at once -- that the extracted ROM
font is byte-correct, that the 16-colour palette matches the hardware, and
that the renderer's glyph and attribute handling is exact.  It does not say
anything about whether the *port* draws the right screens; that is what
tools/compare_screens.py is for.  This is the measuring instrument, calibrated.

Usage:
    python3 tools/verify_pixels.py shots/*.png
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

import numpy as np
from PIL import Image

from monopoly import cga

# Bitmap -> character code.  Several glyphs share a bitmap (0, 32 and 255 are
# all blank); any of them renders identically, so first match wins.
_BY_BITMAP: dict[tuple[int, ...], int] = {}
for _code, _glyph in enumerate(cga.FONT):
    _BY_BITMAP.setdefault(tuple(_glyph), _code)

_RGB_TO_INDEX = {rgb: i for i, rgb in enumerate(cga.PALETTE)}


class DecodeError(Exception):
    pass


class NotTextMode(Exception):
    """The capture is a 320x200 graphics-mode screen, not an 80x25 text one."""


def decode_capture(path: str) -> tuple[cga.Screen, list[tuple[int, int]]]:
    """Turn a 640x400 (or 640x200) DOSBox capture back into a Screen.

    Returns the screen plus the cells where the hardware text cursor was drawn.
    The cursor is generated by the CRTC, not by a character, so those cells are
    reported rather than treated as glyph mismatches.
    """
    img = Image.open(path).convert("RGB")
    a = np.array(img)
    if a.shape[:2] == (200, 320):
        raise NotTextMode(f"{a.shape[1]}x{a.shape[0]} CGA graphics mode")
    if a.shape[0] == 400:
        a = a[::2]  # undo DOSBox's scanline doubling
    if a.shape[:2] != (200, 640):
        raise DecodeError(f"expected 640x400, 640x200 or 320x200, got "
                          f"{a.shape[1]}x{a.shape[0]}")

    scr = cga.Screen()
    cursors: list[tuple[int, int]] = []
    for cy in range(cga.ROWS):
        for cx in range(cga.COLS):
            cell = a[cy * 8:(cy + 1) * 8, cx * 8:(cx + 1) * 8]
            try:
                ch, attr = _decode_cell(cell, cx, cy)
            except DecodeError:
                ch, attr = _decode_cursor_cell(cell, cx, cy)
                cursors.append((cx, cy))
            scr.putcell(cx + 1, cy + 1, ch, attr)
    return scr, cursors


def _decode_cursor_cell(cell: np.ndarray, cx: int, cy: int) -> tuple[int, int]:
    """Decode a cell that the CRTC cursor is overlapping.

    The cursor is a solid bar across the bottom scanlines of the cell.  Strip
    one to four of them and require the remainder to match the top of a glyph.
    """
    for strip in (1, 2, 3, 4):
        head = cell[:8 - strip]
        colors = {tuple(int(v) for v in px) for row in head for px in row}
        if not colors <= set(_RGB_TO_INDEX) or len(colors) > 2:
            continue
        if len(colors) == 1:
            bg = _RGB_TO_INDEX[next(iter(colors))]
            return 0x20, (bg << 4) | bg
        a_rgb, b_rgb = sorted(colors)
        for fg_rgb, fg, bg in ((a_rgb, _RGB_TO_INDEX[a_rgb], _RGB_TO_INDEX[b_rgb]),
                               (b_rgb, _RGB_TO_INDEX[b_rgb], _RGB_TO_INDEX[a_rgb])):
            top = tuple(
                int("".join("1" if tuple(int(v) for v in px) == fg_rgb else "0"
                            for px in row), 2)
                for row in head
            )
            for code, glyph in enumerate(cga.FONT):
                if tuple(glyph[:8 - strip]) == top:
                    return code, (bg << 4) | fg
    raise DecodeError(f"cell ({cx},{cy}) matches no glyph, with or without a cursor")


def _decode_cell(cell: np.ndarray, cx: int, cy: int) -> tuple[int, int]:
    colors = {tuple(int(v) for v in px)
              for row in cell for px in row}
    unknown = colors - set(_RGB_TO_INDEX)
    if unknown:
        raise DecodeError(
            f"cell ({cx},{cy}) uses colours outside the CGA palette: {unknown}")

    if len(colors) == 1:
        c = _RGB_TO_INDEX[next(iter(colors))]
        return 0x20, (c << 4) | c              # blank on that background

    if len(colors) != 2:
        raise DecodeError(
            f"cell ({cx},{cy}) has {len(colors)} colours; text mode allows 2")

    a_rgb, b_rgb = sorted(colors)
    ia, ib = _RGB_TO_INDEX[a_rgb], _RGB_TO_INDEX[b_rgb]

    for fg_rgb, fg, bg in ((a_rgb, ia, ib), (b_rgb, ib, ia)):
        bitmap = tuple(
            int("".join("1" if tuple(int(v) for v in px) == fg_rgb else "0"
                        for px in row), 2)
            for row in cell
        )
        code = _BY_BITMAP.get(bitmap)
        if code is not None:
            return code, (bg << 4) | fg

    raise DecodeError(f"cell ({cx},{cy}) does not match any ROM glyph")


def verify(path: str) -> tuple[str, str]:
    """Returns (status, detail) where status is PASS / FAIL / SKIP."""
    original = Image.open(path).convert("RGB")
    try:
        scr, cursors = decode_capture(path)
    except NotTextMode as exc:
        return "SKIP", f"{exc} - board screen, needs the graphics renderer"
    except DecodeError as exc:
        return "FAIL", str(exc)

    rendered = scr.render(scanline_double=(original.size[1] == 400))
    if rendered.size != original.size:
        return "FAIL", f"size {rendered.size} != {original.size}"

    diff = np.abs(np.array(rendered).astype(int)
                  - np.array(original).astype(int)).sum(axis=2)

    # The CRTC cursor is not a character, so exclude the cells it covers.
    scale = 2 if original.size[1] == 400 else 1
    for cx, cy in cursors:
        diff[cy * 8 * scale:(cy + 1) * 8 * scale, cx * 8:(cx + 1) * 8] = 0

    bad = int((diff > 0).sum())
    total = diff.size
    note = f", {len(cursors)} cursor cell(s) excluded" if cursors else ""
    if bad == 0:
        return "PASS", f"{total} pixels, exact{note}"
    return "FAIL", f"{bad}/{total} pixels differ ({100 * bad / total:.3f}%){note}"


def main(argv: list[str]) -> int:
    paths = argv[1:]
    if not paths:
        print(__doc__)
        return 2
    counts = {"PASS": 0, "FAIL": 0, "SKIP": 0}
    width = max(len(Path(p).name) for p in paths)
    for p in paths:
        status, msg = verify(p)
        counts[status] += 1
        print(f"{status}  {Path(p).name:<{width}}  {msg}")
    print(f"\n{counts['PASS']} exact, {counts['FAIL']} mismatched, "
          f"{counts['SKIP']} skipped (graphics mode)")
    return 1 if counts["FAIL"] else 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
